apiVersion: v1
kind: Service
metadata:
  name: microservice
  labels:
    name: microservice
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 31000
      protocol: TCP
  selector:
    name: microservice
